name: Pull Request Labeler

on: pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/labeler@v4
        with:
          configuration-path: ./.github/labeler_config.yaml
          dot: true
          sync-labels: true
