name: Reusable, test with Cypress

on: workflow_call

jobs:
  reusable-cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node with BW artifactory
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: |
            ./pnpm-lock.json
            ./test/pnpm-lock.json

      - name: Install test dependencies and run component tests
        uses: cypress-io/github-action@v.0.1
        timeout-minutes: 10
        with:
          working-directory: test
          browser: chrome
