name: Test with Cypress, on PR

on:
  pull_request:
    branches: [main]

jobs:
  call-reusable-cypress:
    if: "!contains(github.event.pull_request.labels.*.name, 'ci/cd_only')"
    uses: ./.github/workflows/reusable-cypress.yaml
    secrets:
      CYPRESS_DEFAULT_USER: ${{ secrets.CYPRESS_DEFAULT_USER }}
