name: . Test with Cypress, manual

on: workflow_dispatch

jobs:
  call-reusable-cypress:
    uses: ./.github/workflows/reusable-cypress.yaml
    secrets:
      CYPRESS_DEFAULT_USER: ${{ secrets.CYPRESS_DEFAULT_USER }}
