name: Test with Cypress, on PR

on:
  pull_request:
    branches: [main]

jobs:
  call-reusable-cypress:
    uses: ./.github/workflows/reusable-cypress.yaml
    secrets:
      CYPRESS_DEFAULT_USER: ${{ secrets.CYPRESS_DEFAULT_USER }}
